---
# https://docs.openstack.org/ocata/install-guide-ubuntu/neutron-controller-install.html

- name: db | Ensuring MySQL Is Up And Running
  wait_for:
    port: 3306

- name: db | Creating Neutron DB
  mysql_db:
    name: "{{ openstack_networking_service_controller_db_info['db'] }}"
    state: "present"
  become: true

- name: db | Creating Neutron DB User
  mysql_user:
    name: "{{ openstack_networking_service_controller_db_info['user'] }}"
    host: "{{ item }}"
    priv: "{{ openstack_networking_service_controller_db_info['db'] }}.*:ALL"
    append_privs: true
    password: "{{ openstack_networking_service_controller_db_info['pass'] }}"
  no_log: true
  become: true
  with_items:
    - '{{ ansible_hostname }}'
    - 127.0.0.1
    - '::1'
    - 'localhost'
    - '%'
